[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pydantic-settings>=2.10.1",
    "uvicorn[standard]>=0.30",
    "sqlalchemy>=2.0",
    "psycopg[binary]>=3.1",
    "pydantic[email]>=2.7",
    "python-jose[cryptography]>=3.3",
    "passlib[bcrypt]>=1.7.4",
    "google-auth>=2.28",
    "requests>=2.32",
    "bcrypt<4",
    "joblib>=1.5.2",
    "xarray>=2024.6.0",
    "pandas==2.2.2",
    "numpy==2.0.2",
    "tensorflow==2.18.1",
    "google-meridian==1.2.1",
    "aioredis>=2.0.1",
    "orjson>=3.11.3",
]
